# Generated by Django 5.0.1 on 2025-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(help_text='Level number (0-indexed)', unique=True)),
                ('question', models.TextField(help_text='The riddle text')),
                ('answer', models.CharField(help_text='Correct answer (case-insensitive)', max_length=255)),
                ('security_riddle', models.TextField(help_text='Phase 2 security question')),
                ('security_key', models.CharField(help_text='Phase 2 correct answer', max_length=255)),
                ('hint', models.TextField(help_text='Hint for main riddle')),
                ('security_hint', models.TextField(help_text='Hint for security question')),
                ('category', models.CharField(help_text='Question category', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('points', models.IntegerField(default=10, help_text='Base points for this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['level_number'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_completed_permanently',
            field=models.BooleanField(default=False, help_text='Game completed - no replay allowed'),
        ),
    ]
